layout_spectrum: 0.4418244544666556
typography_spectrum: 0.39493727047411303
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.8892822089929613
  lightness: 0.8914787101472663
  saturation: 0.7179560734050366
  rhythmicContrast: 0.9934694525339447
content_rating:
  adult: false
github: true
opengraph:
  type: ''
  appId: 'https://facebook.com/bison58'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/bef80ed2-2b64-4951-ac83-4778ec3e54b2.jpg
author:
  name: John Sanders
  url: 'http//:delphinusschool.com'
  email: info_delphinusschool@yahoo.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79c17bb9-2bf2-4976-b955-425f4c3fa678.jpg
name: Delphinus School @SLO
navigation:
  - name: Outdoor Adventures and Exploration
    url: 'http://facebook.com/bison58'
    type: external
  - name: >-
      An exceptional outdoor summer prgram for elementary and middle school aged
      students.
    url: 'http://delphinusschool.com'
    type: external
title: 'Outdoor Science Education and Exploration '
content: []
description: >-
  Regional nature awareness summer camps, custom science programs for youth
  groups, special programs for elementary and middle schools, and outdoor
  adventures for families on the Central Coast
purpose:
  - type: email
    url: 'mailto:info_delphinusschool@yahoo.com'
    label: Contact Us
  - type: contact
    url: 'tel:805-458-2970'
    label: Call 805-458-2970
