typography_spectrum: 0.37625002302229404
color:
  brandStrength: 0.026065290439873934
  lightness: 0.09164223494008183
  saturation: 0.07855414808727801
  rhythmicContrast: 0.3222143384627998
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
github: true
opengraph:
  appId: javasilk93401@yahoo.com
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/bef80ed2-2b64-4951-ac83-4778ec3e54b2.jpg
layout_spectrum: 0.8571968663018197
author:
  name: John Sanders
  email: info_delphinusschool@yahoo.com
  url: 'http//:delphinusschool.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/79c17bb9-2bf2-4976-b955-425f4c3fa678.jpg
name: DelphinusSchool@SLO
navigation:
  - name: Outdoor Adventures and Exploration
    url: 'http://facebook.com/bison58'
    type: external
  - name: >-
      An exceptional outdoor summer prgram for elementary and middle school aged
      students.
    url: 'http//:delphinusschool.com'
    type: external
title: Outdoor Science  and Exploration
description: |+

purpose:
  - type: email
    url: 'mailto:info_delphinusschool@yahoo.com'
    label: Contact Us
  - type: contact
    url: 805-458-2970
    label: Call 805-458-2970
